#string functions
str = ("i am studying python")
print (str.endswith("hon"))
str.capitalize()
print (str)
str =  (str.capitalize())
print (str)
print (str.replace("python" , "java"))
print (str.find("am"))
print(str)
print (str.count("a"))